### PR TITLE
Add a healthbar for the enemies

### PR DESCRIPTION
**Pull request by jmf**
With this commit, enemies now have a health bar, that shows their remaining life, floating over them when they don't have maximum HP any more. 
Enemy health bars in action

### CODE REVIEW

**Comment by ObaniGemini** [comment]
The idea is good but I would prefer using **ProgressBar** or **TextureProgress** Nodes.
They permit to do easily what you did with sprites, and maybe even more properly.

**EDIT** : after a discussion on IRC, @jmf proved me by A + B that his choice was better, so this comment can now be considered as unuseful

**Comment by ObaniGemini** [comment]
Also could you add  tween to smooth the healthbar as I did in [this part of Geom](https://github.com/ObaniGemini/Geom/blob/master/Scripts/Base/hud.gd) ?

P.S : this system is meant to work with ascending and descending health

**EDIT** : after a discussion on IRC, @jmf proved me by A + B that his choice was better, so this comment can now be considered as unuseful

**Comment by jmf** [comment]
**Tweening**: The time between hits is quite short, so with tweening, the effect would either be unnoticeable or the health meter would always be lagging behind a little.
**ProgressBar/TextureProgress**: I tested out TextureProgress but wasn't really convinced by how it looked, opposed to my approach, using scaling.

TextureProgress on the right, scaling on the left
Here you can see the difference, TextureProgress on the left, my scaling approach on the right.

**Comment by ObaniGemini** [comment]
I understand the problem...

Then it's a :+1:

**Pull request merged**
